### ISSUE TITLE
"window.RTCPeerConnection is not a constructor"

### ISSUE THREAD

**Issue by streaps** [Johni0702/mumble-client#3]
I'm getting this error with the mumble-web client (webrtc branch) in Firefox 68.7.0esr. 

```
Connection error: TypeError: "window.RTCPeerConnection is not a constructor"
    MumbleClient client.js:196
    connect index.js:27
    tryCallOne core.js:37
    handleResolved core.js:123
    flush browser-raw.js:52
index.js:1204
```

**Comment by Johni0702** [comment]
Working fine for me:
![](https://i.johni0702.de/1vDxv.png)

Do you maybe have some extensions which disable WebRTC or have disabled WebRTC in `about:config` (search for `media.peerconnection.enabled`)?

**Comment by streaps** [comment]
You are right, this is a Firefox problem on my machine. media.peerconnection.enabled is true and the problem persists even with a new profile and no add-ons enabled.

Sorry for the distraction.

**Comment by streaps** [comment]
Firefox in Raspbian Buster is build without WebRTC support, but I couldn't find any documentation about it.  I solved it by installing Firefox from Debian (which is also a bit faster).

about:webrtc should show WebRTC Internals page with statistics. If it's blank, then there is no webrtc support.
